name: Fetch NYC Jobs Daily

on:
  schedule:
    - cron: '0 6 * * *'   # Runs daily at 6 AM UTC
  workflow_dispatch:       # Also allows manual run

jobs:
  fetch_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run the Python script
      run: python fetch_nyc_jobs.py
